#version: '3'

services:

  first-container:
    build:
      context: ../Part_5

  second-container:
    image: nginx
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf